export const SIGN_IN_CONSTANTS = {
    LOGIN_SUBMIT: "Ingresar",
    EMAIL_LABEL: "Correo electronico",
    PASSWORD_LABEL: "Contraseña",
    PASSWORD_PLACEHOLDER: "••••••",
    FORGOT_PASSWORD_DIALOG_TITLE: "Cambiar contraseña",
    EMAIL_PLACEHOLDER: "tu@correo.com",
    FORGOT_PASSWORD_LINK: "¿Olvidaste tu contraseña?",
    FORGOT_PASSWORD_DIALOG_DESCRIPTION: "Ingresa tu correo y te enviaremos un email para cambiar tu contraseña",
    INVALID_EMAIL: "Ingrese un correo valido por favor",
    PASSWORD_TOO_SHORT: "La contraseña debe contener al menos 8 caracteres",
    EMAIL_SENT_SUCCESS: "Un correo ha sido enviado a esta direccion para cambiar la contraseña",
    GENERAL_ERROR: "Oopsy, algo salio mal. Intenta de nuevo",
    PASSWORD_RESET_SUCCESS: "Un correo ha sido enviado a esta direccion para cambiar la contraseña",
    DIALOG_CANCEL: "Cancelar",
    DIALOG_SEND: "Enviar",
}
